### ISSUE TITLE
As a User I want to be able to browse products by category so that I have an easier time finding what I'm looking for

### ISSUE THREAD

**Issue by zachariyaJaveri** [Kas73/SOEN-341-Project#21]
Subtask of Issue #17 

Scenario:
A user is using the browse by category option to view items within that category. They are then redirected to a page with all the items in that category.

Story Points: 2
Priority: Medium
Risk: Low

**Comment by Kas73** [comment]
![image](https://user-images.githubusercontent.com/81095640/158712224-221169e3-5871-4d19-827b-5d63c9a35383.png)

**Comment by zachariyaJaveri** [comment]
Implemented
