### ISSUE TITLE
As a User I want to be able to login to my account on the website

### ISSUE THREAD

**Issue by Kas73** [Kas73/SOEN-341-Project#22]
Subtask of Issue #17

Scenario:
A user is entering their account credentials to log in to the website. Their credentials should be verified and accepted or declined.

Story Points: 3
Priority: Medium
Risk: Low

**Comment by Kas73** [comment]
![image](https://user-images.githubusercontent.com/81095640/158712889-f3035529-f12f-4fa3-8936-1415bc91e34c.png)

**Comment by zachariyaJaveri** [comment]
implmented
