### ISSUE TITLE
As a user I want to be able to create an account so that I can make purchases

### ISSUE THREAD

**Issue by Kas73** [Kas73/SOEN-341-Project#23]
Subtask of Issue #17

Scenario:
A user wants to create an account in order to make purchases from the website and to create listing if made an administrative user as per #26

Story points: 3
Priority: Medium
Risk: Medium

**Comment by zachariyaJaveri** [comment]
Validations still need to be done, but otherwise create an account works

**Comment by Kas73** [comment]
![image](https://user-images.githubusercontent.com/81095640/158713329-47979604-d059-47ee-91a2-c3e3de8d913c.png)

**Comment by zachariyaJaveri** [comment]
implemented
