### ISSUE TITLE
As a User I want to be able to check a single product's details so that I can know if I want to add it to cart

### ISSUE THREAD

**Issue by zachariyaJaveri** [Kas73/SOEN-341-Project#24]
Subtask of Issue #17 

Scenario:
A user is browsing items and then clicks on their desired item. They are then redirected to a page with all the item's pertinent information.

Story Points: 2
Priority: Medium
Risk: Low

**Comment by Kas73** [comment]
![image](https://user-images.githubusercontent.com/81095640/158714247-761fb23e-2a52-4b41-ba6a-f62b9bd9f1ec.png)

**Comment by zachariyaJaveri** [comment]
implemented
