### ISSUE TITLE
As a User I want to be able to search for a product so that it is easier to find what I'm shopping for.

### ISSUE THREAD

**Issue by hughmck** [Kas73/SOEN-341-Project#25]
Subtask of Issue #17

Scenario:
A user is using the search bar to look up an item. They are then redirected to a page with all the item's pertinent information.

Story Points: 3
Priority: Medium
Risk: Low

**Comment by Kas73** [comment]
![image](https://user-images.githubusercontent.com/81095640/158714692-502527bd-2b08-43e3-999b-9b864bbedeaa.png)

**Comment by zachariyaJaveri** [comment]
Implemented
