### ISSUE TITLE
As a user I want to have an administrative account so that I can add products to the shop

### ISSUE THREAD

**Issue by KitchenAce** [Kas73/SOEN-341-Project#26]
Subtask of Issue #17
Key feature of administrative account is the ability to add and remove products.

Scenario: I want to add my products to sell, therefore I need an administrative account. Any other regular account should not be able to add products at will.

Story Points: 4
Priority: Medium
Risk: High

**Comment by Kas73** [comment]
![image](https://user-images.githubusercontent.com/81095640/158715347-4c287038-a5f1-4c1c-8f83-e6bcb7836760.png)

**Comment by zachariyaJaveri** [comment]
implemented
