### ISSUE TITLE
As a user I want to choose the quantity of items I am adding to my cart so that I can buy multiple of the same item

### ISSUE THREAD

**Issue by Kas73** [Kas73/SOEN-341-Project#40]
Subtask of Issue #18

Scenario: 
A user wants to buy 4 of an item in one checkout without having to make multiple purchases

Story Points: 1
Priority: low
Risk: low

**Comment by Kas73** [comment]
![image](https://user-images.githubusercontent.com/81095640/158715877-262f1690-436c-4923-96d5-042e07e34eba.png)

**Comment by zachariyaJaveri** [comment]
implemented
