### ISSUE TITLE
As a user I want to view my cart so that I can finalize my purchase

### ISSUE THREAD

**Issue by Kas73** [Kas73/SOEN-341-Project#41]
Subtask of Issue #18

Scenario:

A user has finalized their shopping and now wishes to view their items one last time before making their purchase.

Story Points: 2
Priority: Medium
Risk: Medium

**Comment by Kas73** [comment]
![image](https://user-images.githubusercontent.com/81095640/158716819-ed9ab686-a99d-4707-975e-c5703df086d3.png)

**Comment by zachariyaJaveri** [comment]
implemented
