### ISSUE TITLE
As a User, I should be able to remove an item from the cart so that I can edit my cart while shopping

### ISSUE THREAD

**Issue by mitchelscottbond** [Kas73/SOEN-341-Project#42]
Subtask of Issue #18 

Scenario: 
A user wants to remove an item from their cart without canceling the cart. 

Story Points: 3
Priority: low
Risk: low

**Comment by Kas73** [comment]
![image](https://user-images.githubusercontent.com/81095640/158716964-041334bb-913d-41c6-942b-3d628b41afef.png)

**Comment by mitchelscottbond** [comment]
Completed
