### ISSUE TITLE
As a user I want to change the quantity of an item from my cart so that I can edit how many of a single item I want

### ISSUE THREAD

**Issue by Kas73** [Kas73/SOEN-341-Project#43]
Subtask of Issue #18

Scenario:
A user changes their mind on the quantity of an item they wish to purchase. They will go to their cart and adjust how many they want. They also can decide to remove the item entirely by setting the quantity to 0

Story Points: 1
Priority: low
Risk: low

**Comment by Kas73** [comment]
![image](https://user-images.githubusercontent.com/81095640/158717219-6f780ef6-3daa-48a5-8a9d-55c1a13597a0.png)

**Comment by mitchelscottbond** [comment]
Completed
