### ISSUE TITLE
As a user I want my shopping cart to remain the same so that I don't have to add items to my cart every time

### ISSUE THREAD

**Issue by Kas73** [Kas73/SOEN-341-Project#44]
Subtask of Issue #18

Scenario:
A user leaves the site to do other things, and when they return, they expect their shopping cart to remain the same

Story Points: 3
Priority: High
Risk: High

**Comment by Kas73** [comment]
![image](https://user-images.githubusercontent.com/81095640/158717843-9c7abc42-ba8d-4396-8c01-4b1a2d34a674.png)

**Comment by mitchelscottbond** [comment]
Completed
