### ISSUE TITLE
As a user I want to add a payment method so that I can make a purchase

### ISSUE THREAD

**Issue by Kas73** [Kas73/SOEN-341-Project#64]
Subtask of Issue #19 

Scenario:
Given that I am checking out the content of my cart I want to complete my purchase after entering and validating my payment information

Story Points: 2
Priority: Low
Risk: Low

**Comment by Kas73** [comment]
![image](https://user-images.githubusercontent.com/81095640/158718748-8aedef79-5a1f-4ca8-be2e-62a32d520ce4.png)

**Comment by ingleankita** [comment]
Completed
