### ISSUE TITLE
As a user I want to add my shipping address to my account so that I can check out without entering it every time

### ISSUE THREAD

**Issue by Kas73** [Kas73/SOEN-341-Project#65]
Subtask of Issue #19

Scenario:
Given that I am checking out the content of my cart I want to complete my purchase after entering and validating my payment information

Story Points: 1
Priority: Low
Risk: Low

**Comment by Kas73** [comment]
![image](https://user-images.githubusercontent.com/81095640/158718941-1932f280-8efa-404b-ae8f-96e51b67ed89.png)

**Comment by ingleankita** [comment]
Completed
