### ISSUE TITLE
As a user I want to see my subtotal after checking out so that I know how much I owe

### ISSUE THREAD

**Issue by Kas73** [Kas73/SOEN-341-Project#66]
Subtask of Issue #19

Scenario:
Given that I have a cart of items I wish to check out I can see how much it costs before I make my purchase. This includes taxes and shipping fee in addition to the sum cost of the items

Story Points: 2
Priority: Medium
Risk: Medium

**Comment by Kas73** [comment]
![image](https://user-images.githubusercontent.com/81095640/158720263-b9f65f5b-67b2-4366-ac29-659f8b64b165.png)

**Comment by ingleankita** [comment]
Completed
