### ISSUE TITLE
As a user I want to place my order and see a confirmation so that I can make a purchase and double check

### ISSUE THREAD

**Issue by Kas73** [Kas73/SOEN-341-Project#67]
Subtask of Issue #19

Scenario:
Given that I have a valid cart I want to place my order and see a confirmation with my shipping address, payment information, total cost, and items in cart

Story Points: 2
Priority: High
Risk: Medium

**Comment by Kas73** [comment]
![image](https://user-images.githubusercontent.com/81095640/158721110-06ee1922-4215-42a2-be76-33b85c730d61.png)

**Comment by ingleankita** [comment]
Completed
