### ISSUE TITLE
As a user I want to see my current order so that I can increase or decrease the number of items in my cart

### ISSUE THREAD

**Issue by Kas73** [Kas73/SOEN-341-Project#68]
Subtask of Issue #19

Scenario:
Given that I have selected items to check out I can change the quantity of each item and then proceed to checkout when I am satisfied

Story Points: 3
Priority: High
Risk: High

**Comment by Kas73** [comment]
![image](https://user-images.githubusercontent.com/81095640/158723009-2946c0df-148a-48ce-9ba6-73e155587598.png)

**Comment by ingleankita** [comment]
Completed
