### ISSUE TITLE
As a user I want to cancel an order after I have placed it so that I can change my mind within a timeframe

### ISSUE THREAD

**Issue by Kas73** [Kas73/SOEN-341-Project#69]
Subtask of Issue #19 

Scenario:
Given that I have placed my order I can cancel within a certain amount of time after placing my order

Story Points: 3
Priority: High
Risk: Medium

**Comment by Kas73** [comment]
![image](https://user-images.githubusercontent.com/81095640/158723502-33c6342b-d542-47e1-92fe-3782b18a9f91.png)

**Comment by mitchelscottbond** [comment]
This was completed with task #107
